server:
  port: 8888
spring:
  application:
    name: mall-config
  profiles:
    active: git #使用本地配置，要使用git存储改为git即可
  cloud:
    config:
      server:
        native: #本地仓库存储
          search-locations: classpath:/config/{application}
        git: #Git仓库存储
          uri: https://gitee.com/betterzzp/doupin-config.git
          username: betterzzp
          password: Aini10000nianlove
          clone-on-start: true
          search-paths: '{application}'
