spring:
  application:
    name: EurekaServer  # 指定注册到eureka server上的服务名称
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false #表示是否注册自身到eureka服务器， 生产配置为true
    fetchRegistry: false #表示是否从其他eureka服务器获得注册信息，生产配置为true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true #是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server

    